### ISSUE TITLE
candlestick example is using ohlc

### ISSUE THREAD

**Issue by cldougl** [plotly/simple-example-chart-apps#3]
https://github.com/plotly/simple-example-chart-apps/blob/master/candlestickplot/app.py#L38

this needs to be changed to type `candlestick` (the syntax is the same for both chart types :) )

**Comment by divyachandran-ds** [comment]
@cldougl  Thank you  for the Review, Done with the corrections, Its changed to candlestick

**Comment by cldougl** [comment]
thanks @divyachandran-ds !!
If you make a pr and add closes or fixes and a link to the issue, when you merge the pr it will automatically close the issue :D 
more info here: https://help.github.com/en/articles/closing-issues-using-keywords
