### ISSUE TITLE
Adding Code Snippet

### ISSUE THREAD

**Issue by divyachandran-ds** [plotly/simple-example-chart-apps#4]
Adding code snippet along with the dash app  to documentation
Suggestions:
Adding the code as a multipage dash app.

**Comment by divyachandran-ds** [comment]
@cldougl logged the issue.

**Comment by cldougl** [comment]
I think adding the code as a multipage dash app is a good idea.
I think it might look good as a tabbed app with an app tab and a code tab.
We should still link back to the source code to that users can clone the entire app (as they'll only see the "app.py" code in the example).
